sonar.projectKey=Tashif-Bashir_acts-sonarcloud
sonar.organization=tashif-bashir

sonar.cfamily.threads=4
sonar.cfamily.compile-commands=/home/runner/work/acts-sonarcloud/acts-sonarcloud/build/compile_commands.json
sonar.coverageReportPaths=coverage.xml

sonar.sources=Core,Plugins,Fatras
sonar.tests=Tests
sonar.exclusions=**/*.py,Tests/**/*,Examples/**/*,thirdparty/**/*
sonar.coverage.exclusions=Examples/**/*,Tests/**/*,thirdparty/**/*

sonar.sourceEncoding=UTF-8
